from enum import Enum


class Role(str, Enum):
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    SOURCE_OWNER = "SOURCE_OWNER"
    DATA_STEWARD = "DATA_STEWARD"
    TECHNICAL_APPROVER = "TECHNICAL_APPROVER"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


EDIT_ROLES = (Role.PLATFORM_ADMIN, Role.SOURCE_OWNER, Role.DATA_STEWARD)
REVIEW_ROLES = (Role.PLATFORM_ADMIN, Role.TECHNICAL_APPROVER)
DATA_ROLES = (Role.PLATFORM_ADMIN, Role.DATA_STEWARD)
