"""initial platform registry and ETL schemas"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "1f0234a8df87"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    for schema in ("platform", "raw", "staging", "trusted", "semantic", "quarantine", "audit"):
        op.execute(sa.schema.CreateSchema(schema, if_not_exists=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="platform",
    )
    op.create_table(
        "ai_usage_log",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("response_id", sa.String(length=200), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_ai_usage_log_tenant_id"), "ai_usage_log", ["tenant_id"], unique=False, schema="audit"
    )
    op.create_table(
        "event_log",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_event_log_tenant_id"), "event_log", ["tenant_id"], unique=False, schema="audit"
    )
    op.create_table(
        "app_user",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("row_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "username"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_app_user_tenant_id"), "app_user", ["tenant_id"], unique=False, schema="platform"
    )
    op.create_table(
        "data_source",
        sa.Column("source_code", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("spreadsheet_id", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("credential_ref", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("sync_schedule", sa.String(length=100), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("last_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "source_code"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_data_source_tenant_id"),
        "data_source",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "nl2sql_request_log",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("question_hash", sa.String(length=64), nullable=False),
        sa.Column("route", sa.String(length=40), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("clarification_question", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform.app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_nl2sql_request_log_tenant_id"),
        "nl2sql_request_log",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "refresh_token",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("jti_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform.app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti_hash"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_refresh_token_tenant_id"),
        "refresh_token",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "validated_query_template",
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("data_product_code", sa.String(length=63), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("examples", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_validated_query_template_tenant_id"),
        "validated_query_template",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "job",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("requested_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(op.f("ix_platform_job_status"), "job", ["status"], unique=False, schema="platform")
    op.create_index(op.f("ix_platform_job_tenant_id"), "job", ["tenant_id"], unique=False, schema="platform")
    op.create_table(
        "source_sheet",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.Column("sheet_name", sa.String(length=200), nullable=False),
        sa.Column("range_a1", sa.String(length=100), nullable=False),
        sa.Column("header_row", sa.Integer(), nullable=False),
        sa.Column("data_start_row", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("active_configuration_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "sheet_id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_source_sheet_tenant_id"),
        "source_sheet",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "configuration_version",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("based_on_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("configuration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("approved_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_response_id", sa.String(length=200), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_sheet_id", "version_no"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_configuration_version_tenant_id"),
        "configuration_version",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_index(
        "uq_active_configuration",
        "configuration_version",
        ["source_sheet_id"],
        unique=True,
        schema="platform",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_foreign_key(
        "fk_sheet_active_configuration",
        "source_sheet",
        "configuration_version",
        ["active_configuration_id"],
        ["id"],
        source_schema="platform",
        referent_schema="platform",
    )
    op.create_table(
        "data_product",
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("code", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("view_name", sa.String(length=63), nullable=False),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("freshness_version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_sheet_id"),
        sa.UniqueConstraint("tenant_id", "code"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_data_product_tenant_id"),
        "data_product",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "profiling_run",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("profile_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_profiling_run_tenant_id"),
        "profiling_run",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "snapshot",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.create_index(op.f("ix_raw_snapshot_tenant_id"), "snapshot", ["tenant_id"], unique=False, schema="raw")
    op.create_table(
        "approval",
        sa.Column("configuration_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["platform.configuration_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_approval_tenant_id"), "approval", ["tenant_id"], unique=False, schema="platform"
    )
    op.create_table(
        "configuration_artifact",
        sa.Column("configuration_version_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("artifact_type", sa.String(length=30), nullable=False),
        sa.Column("file_name", sa.String(length=200), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["configuration_version_id"],
            ["platform.configuration_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_configuration_artifact_tenant_id"),
        "configuration_artifact",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_index(
        "uq_runtime_artifact",
        "configuration_artifact",
        ["configuration_version_id"],
        unique=True,
        schema="platform",
        postgresql_where=sa.text("artifact_type = 'RUNTIME_CONFIG' AND is_current"),
    )
    op.create_table(
        "etl_run",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("configuration_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("rows_extracted", sa.Integer(), nullable=False),
        sa.Column("rows_loaded", sa.Integer(), nullable=False),
        sa.Column("rows_quarantined", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["platform.configuration_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw.snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "run_key"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_etl_run_tenant_id"), "etl_run", ["tenant_id"], unique=False, schema="platform"
    )
    op.create_table(
        "row_issue",
        sa.Column("etl_run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["etl_run_id"],
            ["platform.etl_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="quarantine",
    )
    op.create_index(
        op.f("ix_quarantine_row_issue_tenant_id"),
        "row_issue",
        ["tenant_id"],
        unique=False,
        schema="quarantine",
    )
    op.create_table(
        "row",
        sa.Column("etl_run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["etl_run_id"],
            ["platform.etl_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="staging",
    )
    op.create_index(op.f("ix_staging_row_tenant_id"), "row", ["tenant_id"], unique=False, schema="staging")
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint("fk_sheet_active_configuration", "source_sheet", schema="platform", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_staging_row_tenant_id"), table_name="row", schema="staging")
    op.drop_table("row", schema="staging")
    op.drop_index(op.f("ix_quarantine_row_issue_tenant_id"), table_name="row_issue", schema="quarantine")
    op.drop_table("row_issue", schema="quarantine")
    op.drop_index(op.f("ix_platform_etl_run_tenant_id"), table_name="etl_run", schema="platform")
    op.drop_table("etl_run", schema="platform")
    op.drop_index(
        "uq_runtime_artifact",
        table_name="configuration_artifact",
        schema="platform",
        postgresql_where=sa.text("artifact_type = 'RUNTIME_CONFIG' AND is_current"),
    )
    op.drop_index(
        op.f("ix_platform_configuration_artifact_tenant_id"),
        table_name="configuration_artifact",
        schema="platform",
    )
    op.drop_table("configuration_artifact", schema="platform")
    op.drop_index(op.f("ix_platform_approval_tenant_id"), table_name="approval", schema="platform")
    op.drop_table("approval", schema="platform")
    op.drop_index(op.f("ix_raw_snapshot_tenant_id"), table_name="snapshot", schema="raw")
    op.drop_table("snapshot", schema="raw")
    op.drop_index(op.f("ix_platform_profiling_run_tenant_id"), table_name="profiling_run", schema="platform")
    op.drop_table("profiling_run", schema="platform")
    op.drop_index(op.f("ix_platform_data_product_tenant_id"), table_name="data_product", schema="platform")
    op.drop_table("data_product", schema="platform")
    op.drop_index(
        "uq_active_configuration",
        table_name="configuration_version",
        schema="platform",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(
        op.f("ix_platform_configuration_version_tenant_id"),
        table_name="configuration_version",
        schema="platform",
    )
    op.drop_table("configuration_version", schema="platform")
    op.drop_index(op.f("ix_platform_source_sheet_tenant_id"), table_name="source_sheet", schema="platform")
    op.drop_table("source_sheet", schema="platform")
    op.drop_index(op.f("ix_platform_job_tenant_id"), table_name="job", schema="platform")
    op.drop_index(op.f("ix_platform_job_status"), table_name="job", schema="platform")
    op.drop_table("job", schema="platform")
    op.drop_index(
        op.f("ix_platform_validated_query_template_tenant_id"),
        table_name="validated_query_template",
        schema="platform",
    )
    op.drop_table("validated_query_template", schema="platform")
    op.drop_index(op.f("ix_platform_refresh_token_tenant_id"), table_name="refresh_token", schema="platform")
    op.drop_table("refresh_token", schema="platform")
    op.drop_index(
        op.f("ix_platform_nl2sql_request_log_tenant_id"), table_name="nl2sql_request_log", schema="platform"
    )
    op.drop_table("nl2sql_request_log", schema="platform")
    op.drop_index(op.f("ix_platform_data_source_tenant_id"), table_name="data_source", schema="platform")
    op.drop_table("data_source", schema="platform")
    op.drop_index(op.f("ix_platform_app_user_tenant_id"), table_name="app_user", schema="platform")
    op.drop_table("app_user", schema="platform")
    op.drop_index(op.f("ix_audit_event_log_tenant_id"), table_name="event_log", schema="audit")
    op.drop_table("event_log", schema="audit")
    op.drop_index(op.f("ix_audit_ai_usage_log_tenant_id"), table_name="ai_usage_log", schema="audit")
    op.drop_table("ai_usage_log", schema="audit")
    op.drop_table("tenant", schema="platform")
    # ### end Alembic commands ###
