"""durable import review batches"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "5ab90e816eee"
down_revision = "d83a5f12c906"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_review",
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_sheet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("configuration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("job_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('VALIDATING','AI_REVIEWING','NEEDS_INPUT','READY_FOR_APPROVAL','APPROVED','APPLYING','SUCCEEDED','FAILED','CANCELLED','STALE_REVIEW')",
            name="ck_import_review_status",
        ),
        sa.CheckConstraint("revision_no >= 1 AND generation >= 1", name="ck_import_review_revision"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["platform.job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw.snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["platform.data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_sheet_id"],
            ["platform.source_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "created_by"],
            ["platform.app_user.tenant_id", "platform.app_user.id"],
            name="fk_tenant_import_review_created_by_fa305417",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["platform.job.tenant_id", "platform.job.id"],
            name="fk_tenant_import_review_job_id_ca5ef9aa",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "snapshot_id"],
            ["raw.snapshot.tenant_id", "raw.snapshot.id"],
            name="fk_tenant_import_review_snapshot_id_d039c78c",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_id", "source_sheet_id"],
            [
                "platform.source_sheet.tenant_id",
                "platform.source_sheet.source_id",
                "platform.source_sheet.id",
            ],
            name="fk_import_review_same_source_sheet",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_id"],
            ["platform.data_source.tenant_id", "platform.data_source.id"],
            name="fk_tenant_import_review_source_id_62377396",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_sheet_id"],
            ["platform.source_sheet.tenant_id", "platform.source_sheet.id"],
            name="fk_tenant_import_review_source_sheet_id_ce693451",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_import_review_tenant_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_import_review_status"), "import_review", ["status"], unique=False, schema="platform"
    )
    op.create_index(
        op.f("ix_platform_import_review_tenant_id"),
        "import_review",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_platform_import_review_tenant_id"), table_name="import_review", schema="platform")
    op.drop_index(op.f("ix_platform_import_review_status"), table_name="import_review", schema="platform")
    op.drop_table("import_review", schema="platform")
    # ### end Alembic commands ###
