"""structured import questions and decisions"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "6d1305460956"
down_revision = "5ab90e816eee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_review_row",
        sa.Column("import_review_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transformed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source_row > 0", name="ck_import_review_row_source_row"),
        sa.ForeignKeyConstraint(
            ["import_review_id"],
            ["platform.import_review.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "import_review_id"],
            ["platform.import_review.tenant_id", "platform.import_review.id"],
            name="fk_tenant_import_review_row_import_review_id_ca0d0060",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_review_id", "source_row"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_import_review_row_tenant_id"),
        schema="staging",
    )
    op.create_index(
        op.f("ix_staging_import_review_row_tenant_id"),
        "import_review_row",
        ["tenant_id"],
        unique=False,
        schema="staging",
    )
    op.create_table(
        "import_question",
        sa.Column("import_review_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("staging_row_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("source_column", sa.String(length=63), nullable=True),
        sa.Column("target_column", sa.String(length=63), nullable=True),
        sa.Column("question_key", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("prompt", sa.String(length=2000), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("allowed_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN','ANSWERED','PENDING_APPROVAL','CANCELLED')", name="ck_import_question_status"
        ),
        sa.CheckConstraint("revision_no >= 1", name="ck_import_question_revision"),
        sa.ForeignKeyConstraint(
            ["import_review_id"],
            ["platform.import_review.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staging_row_id"],
            ["staging.import_review_row.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "import_review_id"],
            ["platform.import_review.tenant_id", "platform.import_review.id"],
            name="fk_tenant_import_question_import_review_id_a5e52b7c",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "staging_row_id"],
            ["staging.import_review_row.tenant_id", "staging.import_review_row.id"],
            name="fk_tenant_import_question_staging_row_id_a61b9d17",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_import_question_tenant_id"),
        sa.UniqueConstraint("tenant_id", "import_review_id", "question_key"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_import_question_status"),
        "import_question",
        ["status"],
        unique=False,
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_import_question_tenant_id"),
        "import_question",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    op.create_table(
        "import_decision",
        sa.Column("import_review_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("import_question_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("decided_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("selected_candidate_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("proposed_master_definition_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["platform.app_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_question_id"],
            ["platform.import_question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_review_id"],
            ["platform.import_review.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposed_master_definition_id"],
            ["platform.master_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "decided_by"],
            ["platform.app_user.tenant_id", "platform.app_user.id"],
            name="fk_tenant_import_decision_decided_by_97401a56",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "import_question_id"],
            ["platform.import_question.tenant_id", "platform.import_question.id"],
            name="fk_tenant_import_decision_import_question__671ba66a",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "import_review_id"],
            ["platform.import_review.tenant_id", "platform.import_review.id"],
            name="fk_tenant_import_decision_import_review_id_cc756531",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "proposed_master_definition_id"],
            ["platform.master_definition.tenant_id", "platform.master_definition.id"],
            name="fk_tenant_import_decision_master_proposal",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["platform.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_import_decision_tenant_id"),
        sa.UniqueConstraint("tenant_id", "import_question_id", "revision_no"),
        schema="platform",
    )
    op.create_index(
        op.f("ix_platform_import_decision_tenant_id"),
        "import_decision",
        ["tenant_id"],
        unique=False,
        schema="platform",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_platform_import_decision_tenant_id"), table_name="import_decision", schema="platform"
    )
    op.drop_table("import_decision", schema="platform")
    op.drop_index(
        op.f("ix_platform_import_question_tenant_id"), table_name="import_question", schema="platform"
    )
    op.drop_index(op.f("ix_platform_import_question_status"), table_name="import_question", schema="platform")
    op.drop_table("import_question", schema="platform")
    op.drop_index(
        op.f("ix_staging_import_review_row_tenant_id"), table_name="import_review_row", schema="staging"
    )
    op.drop_table("import_review_row", schema="staging")
    # ### end Alembic commands ###
