"""add taxonomy registry"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="7h74f5b2c3de"; down_revision="7g63f4a1e2bc"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("taxonomy", sa.Column("id",sa.Uuid(as_uuid=False),primary_key=True), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False), sa.Column("tenant_id",sa.Uuid(as_uuid=False),nullable=False), sa.Column("code",sa.String(63),nullable=False), sa.Column("name",sa.String(200),nullable=False), sa.Column("version",sa.Integer(),server_default="1",nullable=False), sa.Column("status",sa.String(20),server_default="DRAFT",nullable=False), sa.Column("is_active",sa.Boolean(),server_default=sa.true(),nullable=False), sa.Column("definition_json",postgresql.JSONB(),server_default=sa.text("'{}'::jsonb"),nullable=False), sa.Column("created_by",sa.Uuid(as_uuid=False),nullable=False), sa.ForeignKeyConstraint(["tenant_id"],["platform.tenant.id"]), sa.ForeignKeyConstraint(["created_by"],["platform.app_user.id"]), sa.UniqueConstraint("tenant_id","code",name="uq_taxonomy_code"), schema="platform")
    op.create_table("taxonomy_term", sa.Column("id",sa.Uuid(as_uuid=False),primary_key=True), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False), sa.Column("tenant_id",sa.Uuid(as_uuid=False),nullable=False), sa.Column("taxonomy_id",sa.Uuid(as_uuid=False),nullable=False), sa.Column("parent_id",sa.Uuid(as_uuid=False)), sa.Column("code",sa.String(63),nullable=False), sa.Column("label",sa.String(200),nullable=False), sa.Column("aliases",postgresql.JSONB(),server_default=sa.text("'[]'::jsonb"),nullable=False), sa.Column("is_active",sa.Boolean(),server_default=sa.true(),nullable=False), sa.ForeignKeyConstraint(["tenant_id"],["platform.tenant.id"]), sa.ForeignKeyConstraint(["taxonomy_id"],["platform.taxonomy.id"]), sa.ForeignKeyConstraint(["parent_id"],["platform.taxonomy_term.id"]), sa.UniqueConstraint("tenant_id","taxonomy_id","code",name="uq_taxonomy_term_code"), schema="platform")
def downgrade():
    op.drop_table("taxonomy_term",schema="platform"); op.drop_table("taxonomy",schema="platform")
